# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vivo-y93.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# { Import Required Services
import sys, res,time, threading, subprocess, webbrowser
# }

from PyQt5.QtCore import pyqtSlot
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(660, 567)

# { remove background frame 
        Interface.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Interface.setAttribute(QtCore.Qt.WA_TranslucentBackground)
# }

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/picture/QC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Interface.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Interface)
        self.widget.setGeometry(QtCore.QRect(30, 30, 611, 511))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(204,0,19,1), stop:1 rgba(200,190,190,1));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(204,0,19,1), stop:1 rgba(200,190,190,1));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color:rgba(0,0,0,0);\n"
"    color:rgba(255,255,255,255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color:rgba(131,96,53,255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91,88,53,255);\n"
"}")
        self.widget.setObjectName("widget")
        self.main_menu = QtWidgets.QLabel(self.widget)
        self.main_menu.setGeometry(QtCore.QRect(50, 30, 241, 430))
        self.main_menu.setStyleSheet("background-color:rgba(0,0,0,140);\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;")
        self.main_menu.setText("")
        self.main_menu.setObjectName("main_menu")
        self.log_process = QtWidgets.QLabel(self.widget)
        self.log_process.setGeometry(QtCore.QRect(270, 60, 291, 430))
        self.log_process.setStyleSheet("background-image: url(:/images/picture/vivo-y93.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;\n"
"border-top-right-radius: 50px;")
        self.log_process.setText("")
        self.log_process.setObjectName("log_process")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 40, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(24)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(90, 400, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(110, 50, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(70, 47, 30, 30))
        self.label_6.setStyleSheet("image: url(:/images/picture/QC.ico);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.reset_frp = QtWidgets.QPushButton(self.widget)
        self.reset_frp.setGeometry(QtCore.QRect(70, 260, 90, 24))
        self.reset_frp.setObjectName("reset_frp")
        self.reset_safe = QtWidgets.QPushButton(self.widget)
        self.reset_safe.setGeometry(QtCore.QRect(170, 260, 90, 24))
        self.reset_safe.setObjectName("reset_safe")
        self.reset_factory = QtWidgets.QPushButton(self.widget)
        self.reset_factory.setGeometry(QtCore.QRect(170, 230, 90, 24))
        self.reset_factory.setObjectName("reset_factory")
        self.reset_imei = QtWidgets.QPushButton(self.widget)
        self.reset_imei.setGeometry(QtCore.QRect(70, 230, 90, 24))
        self.reset_imei.setObjectName("reset_imei")
        self.reboot = QtWidgets.QPushButton(self.widget)
        self.reboot.setGeometry(QtCore.QRect(120, 320, 101, 24))
        self.reboot.setObjectName("reboot")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 90, 191, 121))
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(0, 10, 191, 101))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"color: rgb(255, 255, 255);")
        self.textEdit.setCursorWidth(0)
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 350, 160, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(130, 70, 81, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.unlock_bl = QtWidgets.QPushButton(self.widget)
        self.unlock_bl.setGeometry(QtCore.QRect(70, 290, 91, 23))
        self.unlock_bl.setObjectName("unlock_bl")
        self.relock_bl = QtWidgets.QPushButton(self.widget)
        self.relock_bl.setGeometry(QtCore.QRect(170, 290, 91, 23))
        self.relock_bl.setObjectName("relock_bl")
        self.log_process.raise_()
        self.main_menu.raise_()
        self.pushButton_5.raise_()
        self.pushButton.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.reset_frp.raise_()
        self.reset_safe.raise_()
        self.reset_factory.raise_()
        self.reset_imei.raise_()
        self.reboot.raise_()
        self.groupBox_2.raise_()
        self.gridLayoutWidget.raise_()
        self.label_5.raise_()
        self.unlock_bl.raise_()
        self.relock_bl.raise_()

# { Graphic effect
        self.pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))
# }

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "VIVO Y93 PD1818F - V1.0 [HadiK IT]"))
        self.pushButton_5.setText(_translate("Interface", "ê"))
        self.pushButton.setText(_translate("Interface", "SUPPORT"))
        self.label_7.setText(_translate("Interface", "VIVO Y93 PD1818F"))
        self.reset_frp.setText(_translate("Interface", "RESET FRP"))
        self.reset_safe.setText(_translate("Interface", "RESET SAFE"))
        self.reset_factory.setText(_translate("Interface", " RESET FACTORY"))
        self.reset_imei.setText(_translate("Interface", "RESET IMEI"))
        self.reboot.setText(_translate("Interface", "REBOOT"))
        self.groupBox_2.setTitle(_translate("Interface", "Log : "))
        self.pushButton_2.setText(_translate("Interface", "E"))
        self.pushButton_3.setText(_translate("Interface", "M"))
        self.pushButton_4.setText(_translate("Interface", ")"))
        self.label_5.setText(_translate("Interface", "ONECLICK TOOL"))
        self.unlock_bl.setText(_translate("Interface", "UNLOCK BL"))
        self.relock_bl.setText(_translate("Interface", "RELOCK BL"))

# { Button clicked function
        self.reset_imei.clicked.connect(lambda:self.press_reset_imei())
        self.reset_factory.clicked.connect(lambda:self.press_reset_factory())
        self.reset_frp.clicked.connect(lambda:self.press_reset_frp())
        self.reset_safe.clicked.connect(lambda:self.press_reset_safe())
        self.unlock_bl.clicked.connect(lambda:self.press_unlock_bl())
        self.relock_bl.clicked.connect(lambda:self.press_relock_bl())
        self.reboot.clicked.connect(lambda:self.press_reboot())
        self.pushButton_5.clicked.connect(lambda:Interface.close())
        self.pushButton.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/c/hadikit?sub_confirmation=1'))
        self.pushButton_2.clicked.connect(lambda: webbrowser.open('https://www.facebook.com/f.hadikhoir'))
        self.pushButton_3.clicked.connect(lambda: webbrowser.open('https://www.youtube.com/c/HadiKIT'))
        self.pushButton_4.clicked.connect(lambda: webbrowser.open('https://github.com/HadiKhoirudin/Qualcomm-OneclickTool'))
# }



    @pyqtSlot()
    def press_reset_imei(self):
        command1 = "exec.cmd emmc -reset_imei"
        path = "./data/"
        self.run_command(command1, cwd=path, shell=True)


    @pyqtSlot()
    def press_reset_factory(self):
        command2 = "exec.cmd emmc -reset_factory"
        path = "./data/"
        self.run_command(command2, cwd=path, shell=True)


    @pyqtSlot()
    def press_reset_frp(self):
        command3 = "exec.cmd emmc -reset_frp"
        path = "./data/"
        self.run_command(command3, cwd=path, shell=True)

    @pyqtSlot()
    def press_reset_safe(self):
        command4 = "exec.cmd emmc -reset_safe"
        path = "./data/"
        self.run_command(command4, cwd=path, shell=True)

    @pyqtSlot()
    def press_unlock_bl(self):
        command5 = "exec.cmd emmc -unlock_bl"
        path = "./data/"
        self.run_command(command5, cwd=path, shell=True)

    @pyqtSlot()
    def press_relock_bl(self):
        command6 = "exec.cmd emmc -relock_bl"
        path = "./data/"
        self.run_command(command6, cwd=path, shell=True)

    @pyqtSlot()
    def press_reboot(self):
        command7 = "exec.cmd emmc"
        path = "./data/"
        self.run_command(command7, cwd=path, shell=True)

    @pyqtSlot(str)
    def logging(self, string):
        self.textEdit.append(string.strip())

    def run_command(self, cmd, **kwargs):
        self.textEdit.clear()
        threading.Thread(
            target=self._execute_command, args=(cmd,), kwargs=kwargs, daemon=True
        ).start()

    def _execute_command(self, cmd, **kwargs):
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs
        )
        for line in proc.stdout:
            self.logging(line.decode())



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QtGui.QFontDatabase.addApplicationFont('data/fonts.otf')
    Interface = QtWidgets.QWidget()
    ui = Ui_Interface()
    ui.setupUi(Interface)
    Interface.show()
    sys.exit(app.exec_())
